### ISSUE TITLE
Error showing Xcode 7.3.1 and OSX 10.11

### ISSUE THREAD

**Issue by kapil0408** [4eleven7/iMobileDevice#5]
dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /Users/admin/Library/Developer/Xcode/DerivedData/iMobileDevice-ablnekjututvewcmxctooptgvqgp/Build/Products/Debug/iMobileDevice.framework/Versions/A/iMobileDevice
  Reason: Incompatible library version: iMobileDevice requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

**Comment by kapil0408** [comment]
Any comment on this Please...

**Comment by 4eleven7** [comment]
Unfortunately the project is no longer active nor supported, It is now 3 years old.
Last tested on iOS 7, we're now at iOS 10, no idea if it would work if you managed to resolve your library issues.

However, it states in your first comment... "Incompatible library version: iMobileDevice **requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0**"
You are on version 10, it requires version 12. Update your libxml.
